name: Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [i686-pc-windows-msvc, x86_64-pc-windows-msvc]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Rustup using win.rustup.rs
        run: |
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
          .\rustup-init.exe -y --default-host=${{ matrix.target }} --default-toolchain=none
          del rustup-init.exe
        shell: powershell
      - name: Build
        shell: cmd
        run: cargo build --release
      - name: Rename
        shell: powershell
        run: mv target/release/display_switch.exe target/release/display_switch-${{ matrix.target }}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binaries-${{ matrix.target }}
          path: target/release/display_switch-${{ matrix.target }}.exe
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          path: binaries
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "binaries/Binaries-i686-pc-windows-msvc/*,binaries/Binaries-x86_64-pc-windows-msvc/*"
